// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://djdqaricfdrbkluizxrt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRqZHFhcmljZmRyYmtsdWl6eHJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NzE0MTksImV4cCI6MjA3MjA0NzQxOX0.6oeoaYTpEnfYQHFimN0Y37E27wA7vFOUGEhCn0Fl0bE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});